### ISSUE TITLE
SharedArrayBuffer and Atomics support

### ISSUE THREAD

**Issue by acterhd** [austinksmith/Hamsters.js#10]
Hello. Have you support for these features? Supports in chrome (canary, with flags) and firefox.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics

**Comment by austinksmith** [comment]
I don't have support for them just yet but this is definitely something that I'm interested in adding support for, if you think you can understand the code structure enough don't be afraid to submit a pr. I apologize for the late response the last two weeks have been extremely busy.

**Comment by austinksmith** [comment]
A little bit of guidance on how I'd approach this, first check to see if SharedArrayBuffer support exist, if it does then instead of splitting the array and creating individual arraybuffers, simply create a single sharedarraybuffer and pass a reference to each thread for their "subarray" and simply fetch the subarray from memory, create a new ArrayBuffer inside the thread and use the data there. Technically this would require 2 sharedArrayBuffers most likely one for input and one for output.

**Comment by austinksmith** [comment]
Closing, thanks @acterhd
