### ISSUE TITLE
Perf test show hamster slower than main thread

### ISSUE THREAD

**Issue by acterhd** [austinksmith/Hamsters.js#11]
It's fail? 
http://www.hamsters.io/performance/

PC, Windows 10, Intel i5 6600k. Tested in chrome and nightly (firefox).

**Comment by austinksmith** [comment]
Could you provide some screen shots please, how many times did you run the benchmark and what array size did you choose?

**Comment by austinksmith** [comment]
Please read my explanation for this issue here, https://github.com/austinksmith/Hamsters.js/issues/7

As an example, this is a test case of 400k. On my test machine (Windows 7, i7-3610qm, running chrome) you can see a throughput increase of roughly 63%~ using multiple threads. Something that's hard to do is really maximize the time you spend in a thread, basically what I'm telling you is the provided benchmark is pretty useless as it only does a very simple square root calculation and will not accurately represent the speed ups you can expect when applying parallelism to a more serious task. 
![benhmark](https://cloud.githubusercontent.com/assets/2227747/17532487/c938e9d4-5e4e-11e6-89f8-75950ba30ba3.jpg)

**Comment by acterhd** [comment]
Early main thread been faster, but now I see that slower than multi thread.

**Comment by acterhd** [comment]
![capture](https://cloud.githubusercontent.com/assets/17273637/17542637/14682204-5efd-11e6-88c9-718273c5f91c.PNG)

**Comment by austinksmith** [comment]
So it looks like the test size you are choosing is too small, I recommend you read about these laws regarding parallel computing. There is a point of diminishing returns where the overhead of splitting the data, communicating with the threads, and aggregating the data back together is greater than the benefit you will see. Since the provided benchmark is very simple it's not an ideal case especially with such a small data set, I'd recommend trying a bigger data set say 400-600k integers instead.

https://en.wikipedia.org/wiki/Amdahl%27s_law
https://en.wikipedia.org/wiki/Gustafson%27s_law

**Comment by acterhd** [comment]
I think about kernel principle. For example. Sad that is no possible for GPU at now. :'(

```
var kernel = hamster.buildKernel(function(hamster_space, bufferA, bufferB){
  var thread = hamster_space.threadID;
  var index = hamster_space.globalID;
  bufferA[index] = bufferB[index];
  return 0; //return to empty or null buffer
});

var bufferA = new Uint8Array(...);
var bufferB = new Uint8Array(...);
var err = await kernel({length: 100}, bufferA, bufferB); //where first argument - nil buffer, that are return
```

**Comment by austinksmith** [comment]
I think you meant to post this in response to the other issue request, however there is no reason to rewrite how the system works entirely. Keep in mind the idea is to maintain browser support for IE9+ so this would be a simple feature addition. The shared array buffer would require a range be sent to each thread which would be calculated in the split array function, so thread 1 would get 0-24, thread 2 25-50 etc.

**Comment by austinksmith** [comment]
Also in regards to GPUs, I have plans to use compute shaders from webGL to do arbitrary logic in the future, I just simply haven't had the time to learn them well enough to make use of them.

**Comment by acterhd** [comment]
I have own tests, experiments with multithreading. My rock.js and multithreading very fast. But is not faster than native JS. i.e. typed arrays in my multithreading slower in 5x than simple number. Slower because I creating typed arrays every time. I think about restoring class-based typed arrays, instead of real typed arrays, because real typed arrays with some functional wrapping (even in prototype) are slow. i.e. I every time created typed arrays. 
Same situation with SIMD. Class wrapped simd in 1.5-2x slower than native SIMD. But anyway slower than native version (with pure numbers). Unique that I can say - typed arrays and es6 classes have very bad performance. At least this is so in chrome.

https://github.com/acterhd/rock-js

**Comment by acterhd** [comment]
I'm in their beliefs was a bit wrong. First Chrome does not support SIMD (or SSE, or AVX) like this, and that's a fact. Mozilla Firefox browser and does not know how to properly handle the classes (slow). This is evident from my research in multi-threading performance. Even the chrome is not very draws with typed (on the idea of speed should be higher). And with SIMD wrapper class too, though slow in chrome and without low speed, but not much.

https://github.com/acterhd/rock-js

**Comment by austinksmith** [comment]
I'm not sure I understand what issue ticket you're trying to respond to, please see the above comment for an explanation on the reasons why parallelism especially within javascript and using the very simple provided test case can be a bit unpredictable. As a general rule of thumb however you can expect throughput increases in Chrome and Safari and Firefox, also don't discount the provided benefit of running the tasks on separate threads in the first place. You should never encounter a problem with the main thread locking up due to cpu heavy logic when making use of the library, you can run individual functions in parallel to speed them up as well as run many independent functions concurrently to increase the amount of work you can get done in the same time frame even if you don't speed up each function on it's own.

**Comment by austinksmith** [comment]
@acterhd I know this is an old ticket however, I am wondering if you could try the latest version of the library today and let me know your thoughts on the performance now? Try using version 5.3.9 or version 5.4.0, 5.3.9 will be a little faster but will consume more memory during operation
