### ISSUE TITLE
Can this be used to modify DOM

### ISSUE THREAD

**Issue by Sushil-Dhiver** [austinksmith/Hamsters.js#13]
I have a page where I have 4 canvases displaying images and I currently use javascript timers to loop through images in a set and draw those images on the canvas. but the problem I have is that my timers are synchronous because Javascript is single threaded. so for my 4 canvases, my first canvas animates and then the second and so on. they're not animating concurrently. 

I saw the examples for Hamsters.js and they're all modifying a variable but do they even modify the DOM  as well?

**Comment by austinksmith** [comment]
Could you provide a basic code example of your problem? That will help me understand the question better, in general this is useful for computational work only. If you have logic that needs to for example do some multiplication, string manipulation, encryption is the main use case. 

On a more technical level, the library can't really help do much with the dom itself as threads are sandboxed environments and cannot access the main window thread or dom at all. They're communicated with through a message passing interface so Im not sure it would work for your problem. 

Maybe try something like this will help ;)

```
setTimeout(function() {
   canvas.render();
}, 4);
```

Do that in a loop of some sort and wrap the render in a timeout, due to the way timeout works it might give you some async behavior that you want but it won't in general make the dom more performant.

**Comment by austinksmith** [comment]
Closing this now, thanks @Sushil-Dhiver
