### ISSUE TITLE
[React-Native] Can't find variable: Worker

### ISSUE THREAD

**Issue by flaviotobi** [austinksmith/Hamsters.js#20]
When i try to import, it gives this error:

![screen shot 2017-01-26 at 11 47 21](https://cloud.githubusercontent.com/assets/13239857/22330245/390f8f62-e3bd-11e6-8c84-754fb8d0a882.png)

React-native: v0.31.0
hamster: v3.9.6

**Comment by austinksmith** [comment]
It looks like you're using the IOS version for react native, currently the library has not been developed to work 100% with IOS because of the way IOS handles assigning data to the global scope. In Android this is accomplished by assigning Worker to the global variable which react native uses, unfortunately IOS implements a security check that prevents Worker from being assigned. I haven't had the bandwidth to implement a fix yet that doesn't duplicate the global variable. If you have a way you can think of to accomplish this please submit a pull request unfortunately for the time being I won't be able to tackle this.

**Comment by flaviotobi** [comment]
Thanks for the answer :) 
i'm looking for a quick fix for my problem, if in the mean time i can't find a quick fix i will turn  to a long term fix, and then i will take a look at this  :)
