### ISSUE TITLE
Add support for Promises

### ISSUE THREAD

**Issue by Neoflash1979** [austinksmith/Hamsters.js#42]
How about adding support for Promises. Many asynchronous libraries now offer both callbacks and Promises. I would love to be able to use Hamsters.js with async/await.

**Comment by austinksmith** [comment]
Thanks @Neoflash1979 for the interest in the library, I actually have plans for doing that and quite a bit more though I started at a new job and started my own company recently and it's been eating up the majority of my time (that and a new puppy/car problems keeps me busy haha). So at the moment I am in the process of moving the code base to making use of import and export instead of require and also redoing all the unit tests so when one runs `npm test` it actually does what it should [previous test were jasmine/web based]. 

At the moment those are the highest priority items on my list, then I'd like to add promises and several other features I won't disclose here ;)

**Comment by austinksmith** [comment]
Just a status update, I've completed rewriting the code base into an es6 class and am in the process of adding promises and a ton of other improvements, so they will be included in the next release.

**Comment by austinksmith** [comment]
@Neoflash1979 can you do me a favor and try out the dev branch hamstersPromise method and report back? Thanks.

**Comment by austinksmith** [comment]
You'll need to make use of the params object for everything now..so
```
var params = {
 array: [1, 2, 3, 4, 5, 6, 7, 8]
 threads: 2
 aggregate: true
};
```
```
hamstersPromise(params, functionToRun).then(function(results) {

}).catch(function(error) {
 
});
```

or 

```
await hamstersPromise(params, functionToRun);
```

**Comment by austinksmith** [comment]
Dev branch isn't ready for prime time yet, its a work in progress and can be considered the first release candidate version, not all features are working at the moment.

**Comment by Neoflash1979** [comment]
@austinksmith Ok, will take a look and report back. Is there anything in particular you would like me to test?

**Comment by austinksmith** [comment]
@Neoflash1979 nothing crazy, just make sure you can call the library and run a function on its own thread and you can run a function across multiple threads like a for loop going through an array

**Comment by Neoflash1979** [comment]
@austinksmith I played with it a little and everything seems to work properly. It's great to be able to use it inside an async function.

**Comment by austinksmith** [comment]
@Neoflash1979 awesome, did you test with Node.js? Which version did you use?

 I still need to wrap up the following before the new version will be live.

1. Fix legacy fallback support
2. Write more jasmine test cases
3. Investigate an issue with chrome on mobile
4. Some other small tweaks for the queue & cache system

As you can see its a big change from before so it's taken quite a while but everything has been dramatically simplified.

**Comment by Neoflash1979** [comment]
@austinksmith Good work. This is a really neat library. I tried it in Node.js version 8.1.3 and also in the latest version of Chrome and I didn't run into any issues.

**Comment by austinksmith** [comment]
@Neoflash1979 thanks, I'm going to be marking this as resolved now since you are able to use it at the moment. Though keep in mind the dev branch is not the final iteration of the new version, also I should note there will be some changes to the licensing agreement alongside the new release due to some bad actors which cost me a somewhat  significant sum of money to put a stop to, though it shouldn't impact the mass majority of users in anyway. If you like the project I welcome feature suggestions and pull requests and monetary donations as well. Even doing the testing like you did for node is very appreciated, this library was no small undertaking to get where it is and just the amount of time required to test different hardware configurations and devices can be overwhelming at times. 

I might also offer a message board on the website to allow people to share projects or showoff projects they've used with the library and what kind of performance increase they've seen, let me know if that's something of interest to you. I think it would be pretty neat and maybe it would help crowd source some of the testing since high core count machines (above 16 threads) are something I will need to optimize for in future releases.

**Comment by austinksmith** [comment]
@Neoflash1979 Version 5.0.0 is officially live with support for promises, you will want to use this as it includes some other fixes your version didnt have. Thanks!

https://github.com/austinksmith/Hamsters.js/releases/tag/v5.0.0
