### ISSUE TITLE
error _slicedToArray is not defined  

### ISSUE THREAD

**Issue by darkworks** [austinksmith/Hamsters.js#44]
thanks for the amazing lib :) i was wondering when the new version will be released as i have noticed its logger is improved with current latest version i have bit hard time with debugging as recently i have encountered error when i have started using hamster along webpacks 

```
Error Hamster #0: Line 431 in : Uncaught ReferenceError: _slicedToArray is not defined
onerror @ hamsters.js:610
```

**Comment by austinksmith** [comment]
Hey @darkworks the dev branch shouldn't be used right now since its under changes whenever I get the opportunity to work on it. I cannot give an exact ETA on when the next version will be released since its dependent on when I get some free time to sit down and concentrate which seems to be pretty rare lately. 

I don't know if you've seen the website lately but I've been working on that and adding more parallel execution examples which also eats up a good bit of time, just keep using v4.2.1 for now and when the new version releases it will be well worth the wait.

**Comment by austinksmith** [comment]
I am also mulling over the need to test for newer higher core count processors and unfortunately do not have the ability to allocate funds towards new hardware purchases right now. I would love to get my hands on a 32 thread AMD threadripper processor and validate and test the library against that, right now I only have access to 8 thread Core i7 machines which is mainly what the library was developed against from the beginning. I may create a bug bounty to get that to happen if there is enough interest.

**Comment by darkworks** [comment]
ok i will wait :) for the new version , good that i fixed the error 

thanks

**Comment by austinksmith** [comment]
No problem, thanks @darkworks
