### ISSUE TITLE
ERROR:  _habitat2.default.SharedWorker is not a constructor [React Native]

### ISSUE THREAD

**Issue by JonathanGVfrenton** [austinksmith/Hamsters.js#48]
### New Issue Report

* ***What version of the library are you using?***

"hamsters.js": "^5.0.0" + "react-native-threads": "^0.0.10"

* ***What operating system are you seeing the issue on?***

MacOS

* ***Which platform (and or) browser are you seeing the issue on?***

React-Native
    "react": "^16.3.0-alpha.1",
    "react-native": "0.54.0",

* ***Example logic***

Trying to run the code described on your wiki, within a brand new sample app created with 
Step 1
    react-native init HamstersTest

Step 2
    Babel es2015 dependencies

Step 3

import { Thread } from 'react-native-threads';
import hamsters from 'hamsters.js';
...
hamsters.init({
  Worker: Thread
});
...
executeHamsters() {
    var params = {
      array: [1, 2, 3, 4],
      threads: 4
    };
  
    hamsters.run(params, function() {
      for(var i = 0; i < params.array; i++) {
        rtn.data.push(params.array[i] * 4);
      }
    }, function(results) {
      console.debug('results', results);
    });
  }

**Comment by austinksmith** [comment]
That's weird because reactnative shouldn't be trying to use SharedWorkers at all but i digress.

Try running init like so..

```js
hamsters.init({Worker: Thread, SharedWorker: Thread})
```

**Comment by JonathanGVfrenton** [comment]
With the new init, I got a different error:   Can't find variable: BlobBuilder

StackTrace:
  createDataBlob (data.js:190:23)
  generateWorkerBlob (data.js:113:38)
  spawnHamsters (pool.js:99:44)
  initializeLibrary (hamsters.js:54:31)
  ...
  myCode calling: 
  hamsters.init({
      Worker: Thread, 
      SharedWorker: Thread
    });

Looking at the source, data.js:190:23:
      ...
      let BlobMaker = (BlobBuilder || WebKitBlobBuilder || MozBlobBuilder || MSBlobBuilder);
      ...

Thanks for your help.

**Comment by austinksmith** [comment]
Would you be willing to test some changes I make with the dev branch?

**Comment by JonathanGVfrenton** [comment]
Absolutely, yes.

I’m off for the day, but happy to start next week.

Thanks in advance for your help.

**Comment by austinksmith** [comment]
Alright, I think I located an fixed the bug..typo between `this.webWorker` and `this.webWorker()` I also tweaked the data blob creation to be more fail safe, give it a shot and let me know how it goes. Thanks.

**Comment by austinksmith** [comment]
Any luck?

**Comment by JonathanGVfrenton** [comment]
Hi, 

My apologies, I had to follow other priorities for the day.  But, I’ll re-visit these tests tomorrow first thing in the morning.

regards,

**Comment by austinksmith** [comment]
No worries just keep me posted

**Comment by JonathanGVfrenton** [comment]
Hi, 

Using lastest development version I’m getting this error:




Is there any chance, this worker implementation is not suitable for working with hamsters?

import { Thread } from 'react-native-threads';

Thanks!

**Comment by JonathanGVfrenton** [comment]
Another test, same latest dev but running on a bigger app 
("react": "16.0.0-alpha.12", "react-native": "0.47.1",) is showing a different error:
![image](https://user-images.githubusercontent.com/36979731/37068839-5e323702-2176-11e8-8821-341787f8f0e6.png)

**Comment by austinksmith** [comment]
That's actually what I was hoping to see, somewhere along the lines the library is mixing react native and another environment. Until the next release of RN, it doesn't have support for data blob creation, the latest version was supposed to skip using data blobs for react native entirely but it looks like part of the problem was not fixed. 

I will be pushing another fix this morning into dev branch that you can try, it should hopefully avoid using data blobs all together but if we can't get it working then we might have to wait until the next release of react native to officially land.

**Comment by austinksmith** [comment]
Ok sorry for the delay, give it a shot now and report back we should be close to the finish line now

**Comment by austinksmith** [comment]
Also make sure when you test to remove "SharedWorker" from your hamsters.init call so you're only passing Worker this time

**Comment by austinksmith** [comment]
Basically the issue ultimately came down to environment detection, the library has to do quite a bit of self modification during execution in order to support so many environments which means if something goes wrong during the detection process then it will attempt to use an unsupported feature like data blobs in this case. 

In core/habitat.js there are two functions that attempt to detect if we're running in a browser and if we're running in a react native environment.

```js
  /**
  * @function isReactNative - Detects if execution environment is reactNative
  */
  isReactNative() {
    return !this.isNode() && typeof global === 'object';
  }
```

```js
  /**
  * @function isBrowser - Detects if execution environment is a browser
  */
  isBrowser() {
    return typeof window === "object";
  }
```

So for some reason, and this might possibly be related to using webpack and babel but normally window should be undefined within react native but in your case its defined and it's an object so the library assumed we were running in a browser, what is weird though is the `isReactNative` call also returned true so for some reason and again Im starting to think this is because of babel/webpack adding some emulated browser stuff during the build process, the tweaks I made should get us past the original error and we should hopefully be good to go. 

If when you test it fails again there is only 1 more line I can think to change that *might* get us past this issue, unless you can think of a more reliable way to detect that we're running in react native.

**Comment by austinksmith** [comment]
Please let me know when you test if the latest dev branch tweaks worked

**Comment by austinksmith** [comment]
I should also add that in the dev branch is a new feature to allow you to override the automatic environment detection so you can now do something like this...


```js
hamsters.init({
  browser: false,
  reactNative: true
});
```

**Comment by JonathanGVfrenton** [comment]
Thanks, again for your time and patience, with the latest version from dev, using:

hamsters.init({
  Worker: Thread,
  //SharedWorker: Thread   --> with or without the SharedWorker
  browser: false,
  reactNative: true
});

![image](https://user-images.githubusercontent.com/36979731/37320437-55cf90d8-2639-11e8-9ee6-ab57f91d8bbf.png)

//- Another test ------------------------------
hamsters.init({
  Worker: Thread,
  SharedWorker: Thread   // With or without this line same error
});
![image](https://user-images.githubusercontent.com/36979731/37320513-a3cc2ec2-2639-11e8-848c-b64fb86b6e47.png)


//- Another test ------------------------------

**Comment by austinksmith** [comment]
The error "Only js files are supported" is what we wanted, that means we're past the environment detection issues. I'll make another tweak in a few and we should hopefully be good to roll.

IE10 has security issues, Node and ReactNative don't come with web worker support so what I have been doing for node is simply passing the logic we want executed inside the worker directly. I guess react native threads doesn't want us to do that (actually follows the spec more) then I have to modify the logic so that react native loads from the `src/common/wheel.js` file instead of trying to create data blobs or directly execute the logic.

**Comment by austinksmith** [comment]
Ok cool give it a shot as soon as you can and report back, in the new dev branch there is a folder under the build directory called common, it basically is just an exact copy of the same file that's under src/common , for reactNative it should now load that file.

It's a relative path and since we are executing from within the build directory our path is going to be 

`./common/hamstersWheel.js`

```js
    if(hamstersHabitat.reactNative || hamstersHabitat.ie10) {
      return new hamstersHabitat.Worker('./common/hamstersWheel.js');
    }
```
Thanks!

**Comment by JonathanGVfrenton** [comment]
Following the setup steps, copy the src folder and paste it within my project, I got this import:

import { Thread } from 'react-native-threads';
import hamsters from './app/utils/hamsters/hamsters';

iOS:
![image](https://user-images.githubusercontent.com/36979731/37507257-3a54dc06-28b3-11e8-8329-7bd97ee03812.png)

Android:
![image](https://user-images.githubusercontent.com/36979731/37507371-c23b2954-28b3-11e8-9c26-3b328e239eb3.png)

Thanks

**Comment by austinksmith** [comment]
Don't copy the src folder, copy the build folder..package.json references
the build/hamsters file..if you copy the src folder then you must copy the
common folder INTO the src directory

**Comment by austinksmith** [comment]
The folder structure looks like this..


build/hamsters.node.js <- referenced in package.json
build/common/hamstersWheel.js 

When it loads, it's expecting the common folder to be in the same directory as the hamsters.js file, if you copied the src directory then the common folder will be in the parent directory and not the same directory

**Comment by austinksmith** [comment]
I just went ahead and changed it permanently in the project structure so that way common is always nested under src/core and the build process ensures it gets placed properly in the build directory so regardless of how you use the library it *should* load the file

**Comment by JonathanGVfrenton** [comment]
I have two options for setup your library:

1) Download your code from dev and copy (build or src contents, tried both already) within an app/util/hamsters/ folder
import { Thread } from 'react-native-threads';
import hamsters from './app/utils/hamsters/hamsters';

hamsters.init({
  Worker: Thread
});

 executeHamsters() {
    var params = {
      array: [1, 2, 3, 4],
      threads: 4
    };
    hamsters.run(params, function() {
      for(var i = 0; i < params.array; i++) {
        rtn.data.push(params.array[i] * 4);
      }
    }, function(results) {
      console.debug('results', results);
    });
  }
Result using src folder
![image](https://user-images.githubusercontent.com/36979731/37618691-b0701042-2b7c-11e8-9221-347b082a4ebc.png)

Result using build folder
![image](https://user-images.githubusercontent.com/36979731/37618872-2db64ddc-2b7d-11e8-8d3d-40ab6f9af2e5.png)

2) run yarn add hamsters.js, it will download the latest release on node_modules, so I'll overwrite the contents with dev version:
import { Thread } from 'react-native-threads';
var hamsters = require('hamsters.js');

hamsters.init({
  Worker: Thread
});

 executeHamsters() {
    var params = {
      array: [1, 2, 3, 4],
      threads: 4
    };
    hamsters.run(params, function() {
      for(var i = 0; i < params.array; i++) {
        rtn.data.push(params.array[i] * 4);
      }
    }, function(results) {
      console.debug('results', results);
    });
  }
![image](https://user-images.githubusercontent.com/36979731/37618240-463b9ef4-2b7b-11e8-9aba-3c1b5ffd2fe6.png)

**Comment by austinksmith** [comment]
Read the message you are receiving and move the folder to the appropriate location, its clear react native is expecting common to be in your root project directory

**Comment by JonathanGVfrenton** [comment]
I moved common folder to the root.  Now I'm getting this.

![image](https://user-images.githubusercontent.com/36979731/37621116-aa17da2a-2b83-11e8-8736-84f50e4e07f4.png)

**Comment by austinksmith** [comment]
Fixed the typo

https://github.com/austinksmith/Hamsters.js/commit/16fd83c5940565374acf13b276aba43789260535

**Comment by JonathanGVfrenton** [comment]
With latest version on commit d0b602c
![image](https://user-images.githubusercontent.com/36979731/37621845-c97bfae8-2b85-11e8-8a7e-3d0034fc7f64.png)

**Comment by austinksmith** [comment]
That's annoying since it works everywhere else, give the latest changes a shot..changed it from adding an event listener for the message to just assigning onmessage

**Comment by JonathanGVfrenton** [comment]
I got a similar error with onmessage:

![image](https://user-images.githubusercontent.com/36979731/37633537-64682cc0-2bb8-11e8-829c-74ad594903dd.png)

Thanks.

**Comment by austinksmith** [comment]
As a hopeful permanent solution to this problem i have created a new wheel file specifically tailored for react native threads, though this is outside the scope of the support I would normally provide the amount of pain its been to get this working makes me want to see it through to the end.

This new file is called rnHamstersWheel.js and it's under the common folder as well, the library has been updated to reference this new file and attempt to use it. You will need to place this file under your common directory and update your src copy as well. 

```js
/* jshint esversion: 5, curly: true, eqeqeq: true, forin: true */

/***********************************************************************************
* Title: Hamsters.js                                                               *
* Description: 100% Vanilla Javascript Multithreading & Parallel Execution Library *
* Author: Austin K. Smith                                                          *
* Contact: austin@asmithdev.com                                                    *  
* Copyright: 2015 Austin K. Smith - austin@asmithdev.com                           * 
* License: Artistic License 2.0                                                    *
***********************************************************************************/

import { self } from 'react-native-threads';

(function () {

   'use strict';

    self.params = {};
    self.rtn = {};

    self.onmessage = function(incomingMessage) {
      params = incomingMessage.data;
      rtn = {
        data: [],
        dataType: (params.dataType ? params.dataType.toLowerCase() : null),
        threadStart: Date.now()
      };
      new Function(params.hamstersJob)();
      rtn.threadEnd = Date.now();
      postMessage(prepareReturn(rtn), prepareTransferBuffers(rtn));
    };

    function prepareReturn(returnObject) {
      var dataType = returnObject.dataType;
      if(dataType) {
        returnObject.data = typedArrayFromBuffer(dataType, returnObject.data);
      }
      return returnObject;
    }

    function typedArrayFromBuffer(dataType, buffer) {
      var types = {
        'uint32': Uint32Array,
        'uint16': Uint16Array,
        'uint8': Uint8Array,
        'uint8clamped': Uint8ClampedArray,
        'int32': Int32Array,
        'int16': Int16Array,
        'int8': Int8Array,
        'float32': Float32Array,
        'float64': Float64Array
      };
      if (!types[dataType]) {
        return buffer;
      }
      return new types[dataType](buffer);
    }

    function prepareTransferBuffers(hamsterFood) {
      var buffers = [];
      var key = null;
      for (key in hamsterFood) {
        if (hamsterFood.hasOwnProperty(key) && hamsterFood[key]) {
          if(hamsterFood[key].buffer) {
            buffers.push(hamsterFood[key].buffer);
          } else if(Array.isArray(hamsterFood[key]) && typeof ArrayBuffer !== 'undefined') {
            buffers.push(new ArrayBuffer(hamsterFood[key]));
          }
        }
      }
      return buffers;
    }

}());
```

This will import the `self` variable from react native threads and it will assign `onmessage` to the self variable that was imported.

**Comment by JonathanGVfrenton** [comment]
Good progress, but still is not working as expected:

![image](https://user-images.githubusercontent.com/36979731/37634796-a8c4bb9a-2bbd-11e8-9e94-670cb278764f.png)

**Comment by austinksmith** [comment]
That doesn't look to be a problem within the Hamsters.js library anymore, however something to note is that react native threads says that you can only use strings to communicate meaning that performance is not going to be ideal. I can modify the library to only use string communication for react native but that means react native threads cannot support transferable objects

**Comment by austinksmith** [comment]
I've modified the logic to stringify the data and parse it when communicating, this should ensure the library is only handling string's as required by react native threads, though like I warned this will have a negative impact on performance due to higher communication overhead between threads. Therefore my recommendation for you to extract the best performance is to use a low global thread count of say 4 or less.

```js
hamsters.init({
  maxThreads: 2
});
```

**Comment by austinksmith** [comment]
Please report back when you get the opportunity, I am going to mark this ticket as resolved if I don't hear anything soon. Thanks!

**Comment by JonathanGVfrenton** [comment]
using threads: 3
on iOS:
![image](https://user-images.githubusercontent.com/36979731/37776904-f8b5cc08-2dab-11e8-9e8e-511f84a3661f.png)

on Android:
![image](https://user-images.githubusercontent.com/36979731/37777452-2f4c04e8-2dad-11e8-821a-8f0d0dae8fea.png)

**Comment by JonathanGVfrenton** [comment]
Herewith you can find the source I'm using for testing.

Please, give it a try.
[TestHamsters.zip](https://github.com/austinksmith/Hamsters.js/files/1838013/TestHamsters.zip)

**Comment by austinksmith** [comment]
I am going to mark this ticket as resolved and close it out, the problems you are seeing do not appear to have anything to do with the library itself. You will need to debug yourself why calling `JSON.stringify` on an object containing an array would fail within your react native appication, this has already far exceeded the typical support given for the project. Hamsters.js free support is limited to purely problems with the library itself, I have already extended support to the point of custom tailoring the react native logic to work with the specific worker implementation you are using as a note I looked at your example and you are not using the environment override in your initialization as I recommended, please be sure to follow the guidance as I laid out. If you want custom support specifically for your application you can request a quote for consulting services but support for this project will not be extended to debugging specific applications especially if that application is not following the guidance as laid out before hand. 

```
  /**
  * @function messageWorker - Prepares message to send to thread
  * @param {worker} hamster - Thread to message
  * @param {object} hamsterFood - Message to send to thread
  */  
  messageWorker(hamster, hamsterFood) {
....
    **if(hamstersHabitat.reactNative) {
      return hamster.postMessage(JSON.stringify(hamsterFood));
    }**
...
  }
```

You need to also follow my instructions to a tee, you are skipping the most critical new feature I added in attempts to resolve your problems which is the environment overrides.

 My takeaway from the error you are seeing is that calling stringify on an object is a completely normal operation that shouldn't have any problems completing. so this points to a problem with your app configuration preventing conversion of an array into a string *or* security restrictions preventing the conversion within react native somewhere and that would require a ticket within the react native project page. If you read the documentation on react native threads they mention that communication between threads MUST take place using strings and strings only, the library is turning the objects it normally uses internally into strings using the built in `JSON.stringify` and `JSON.parse` methods, if these methods are failing for you there is nothing that can be done on my end to resolve your problems.

A few minutes of googling should lead you to the right answer, also be sure to test the same logic using Android as well...a hint I can give you is that this is most likely a problem with your swift setup and the same problem would not be displayed if you ran an android emulation using the same app. 

A new release will be prepared soon that will include these patches and the additional file for this worker implementation as well as updated documentation on how to get react native working more smoothly, lastly please support the project using our open collective, I am only one person managing this and supporting it, thanks.

https://opencollective.com/hamstersjs

**Comment by JonathanGVfrenton** [comment]
I really appreciate your help, I have a different standpoint.

It is not my application, I've been trying with a simple react-native application created from scratch only with the code for testing your library, the problem is completely isolated in your library, or the compatibility with a brand new rn application, so we can help each other.  I have been following your advices, doing trials and errors, if the latest version of the code do not have them, does not mean I'm not following instructions, it just the last test.  

I asked you if the worker thread library was suitable with your application, or please provide advice.  I have no custom code, just a brand new react-native application with the development version of your library and it is not working.

I think if you really want to provide support to react-native, you should try it yourself, and update the documentation on your web site, on how to install and make it work.

Thanks again for all your help.

**Comment by austinksmith** [comment]
```
I asked you if the worker thread library was suitable with your application, or please provide advice. I have no custom code, just a brand new react-native application with the development version of your library and it is not working.
```

This is exactly what I have done for you.

Here are the following new features that have been added to the library specifically to resolve your problems.

1. Environment overrides, force the library to use reactNative execution path, a critical step you are skipping *right now* which is the *EXACT* cause of your current bug, read the message you are seeing does the error message say anything about Hamsters.js or any files within the Hamsters.js library methods? The answer is no, the failure is the RTC communcation, which since you are ignoring my advice it is attempting to send *NON* string data to the worker which obviously fails because as Ive mentioned several times and the react-native threads library mentions, only strings can be passed. 

2. A custom made external worker file to use the library that imports your worker implementation and ensures communication only take place using stringified objects 

3. Modified the library execution to resolve environment mismatch detection problems and ensure that when operating within react native all communication uses strings as required by react-native-threads


```
I think if you really want to provide support to react-native, you should try it yourself, and update the documentation on your web site, on how to install and make it work.
```

I think you should follow the instructions as laid out, including the environment override feature that was made specifically for you. If you want to donate to the project or lend access to IOS devices or a Mac OS system for debugging then I could certaintly "try it myself" but as I mentioned since the creation of your ticket I do not have access to these devices for testing at the moment and would need your collaboration to get the issue resolved. 

The issue is now resolved, follow my instructions and your problem will disappear...also can you not set a break point on the exact failure point?

**Comment by austinksmith** [comment]
Hamsters.js is an open source vanilla web-worker based *javascript* library, all the library operations adhere the web worker specification to the fullest extent possible, if using stringified objects is not possible within react-native-threads then that is not a problem within this library anymore. Environments must adhere to the worker specification, if they do not adhere to the specification then attempts will be made to get around that like using strings in this case, but if using strings fails then that is outside the scope of what this library can do. Its a javacript library, if react-native-threads has problems and doesn't work using the standardized javascript ES5 methods like `parse` and `stringify` then that requires a ticket with their project page and there is nothing I can reasonably do to fix that.

**Comment by JonathanGVfrenton** [comment]
Thank you so much for all your help, now using the configuration you provided, without react-native-threads, it is working.

Thanks for your patience.

**Comment by austinksmith** [comment]
Great, but a word of warning. When you use the library without a third party worker implementation the library will fallback to legacy operation mode, this means that the library will still work and you can still write your logic to use the library and take advantage of some of the library features but you are *not* getting the benefit of multiple threads and ALL execution is taking place on the main thread so you are not gaining much extra performance by using the library.

The only way the library will be truly useful for you is if we can get communication with react-native-threads or a different web worker implementation working properly so that way you can use all your cores instead of just one, right now you're basically able to write your code, guarantee that it works in react native, node, and browsers but you arent getting the performance you want yet.
