### ISSUE TITLE
Cannot read property 'buffer' of undefined."

### ISSUE THREAD

**Issue by jfuehner** [austinksmith/Hamsters.js#61]
I'm looking at upgrading from v4.2.1 to v5.1.2. From what I can see it should just be a drop in replacement in terms of syntax. My code runs fine with v4.2.1 but, when I run with v5.1.2 I receive an error stating **"Cannot read property 'buffer' of undefined."**

I tracked down the error to the **prepareTransferBuffers** method in data.js. The line that checks **`hamsterFood[key].buffer`** is failing on the first key **"array"**.

The key "array" is undefined therefore does not have a "buffer" property which is causing that function to fail.

Thoughts on how to get around this?

* ***What version of the library are you using?***

v5.1.2

* ***What operating system are you seeing the issue on?***

Windows 10

* ***Which platform (and or) browser are you seeing the issue on?***

Using Hamsters via NPM with WebPack for a Vue JS application. Running in Chrome v64.

**Comment by austinksmith** [comment]
Hmm ok, I started a new position lately and haven't been taking anytime to work on this in the last couple weeks. I have some plans to fix some issues already discovered in the latest release and I will be sure to include this as a fix as well. Do you have an example of the function you are trying to run?

**Comment by austinksmith** [comment]
Also the new version, i'm taking a different approach to the parallelization part of the library so invoking loops using multiple threads should be significantly faster across the board as I'll be only splitting data and aggregating data when it's used instead of doing all the data splitting up front and aggregating results at the end..this should reduce overhead quite a bit and show some good speed up especially on cpu's that have weaker single threaded performance.

**Comment by austinksmith** [comment]
I'm making good progress on the new release and will do what I can to eliminate the problem you are seeing, if you can provide an example function that would help quite a bit...early results are showing massive performance improvements with my new approach to handling the data like 1000+% faster

**Comment by austinksmith** [comment]
https://github.com/austinksmith/Hamsters.js/issues/67

**Comment by austinksmith** [comment]
Hey @jfuehner I know it's been a long time since I updated this bug ticket, however I did just release a new Hamsters version today that should hopefully resolve your issues. Please take a look at https://github.com/austinksmith/Hamsters.js/releases/tag/v5.1.3 and let me know if it resolves your problem. thanks!
