### ISSUE TITLE
Your country is blocked from accessing this content.

### ISSUE THREAD

**Issue by twoco** [austinksmith/Hamsters.js#68]
I can't access to the https://www.hamsters.io/ website. It just displays a text `Your country is blocked from accessing this content.`. I live in germany. Because article 13? But why?

![image](https://user-images.githubusercontent.com/53160891/71446589-46018780-2725-11ea-83fa-c40aa47f2cc0.png)

**Comment by austinksmith** [comment]
Happy Holidays @twoco , I apologize for the inconvenience. Truth be told there are a multitude of reasons that I have currently restricted the website to the US and US territories, primarily due to on going organized harassment and theft of intellectual property. I am in talks with some intellectual property lawyers and working on doing what I can to protect the library from theft and it was suggested to me to restrict the website to the US market for the time being so it doesn't have anything to do with Article 13, and once I've finished resolving this problem the site will be open again to every country.

I went ahead and added Germany as an accepted country code so you should be able to access the website again, just a heads up the website has changed quite a bit in the last couple weeks. Let me know if you need any other assistance, thanks.
