### ISSUE TITLE
Anyone use hamesters.js successfully in Chrome Browser ?

### ISSUE THREAD

**Issue by daoxian** [austinksmith/Hamsters.js#73]
I've met this problem with v5.1.3:
![image](https://user-images.githubusercontent.com/34263430/106085172-a948bf00-615a-11eb-9f31-c1d8a330ebb0.png)
codes here:

>     let params = {
>       threads:10,
>     };
>     hamstersJs.hamstersRun(params,
>       ()=>{ },
>       (result)=>{},
>       (e)=>{});
> 

Any suggestions or tips are appreciated!

**Comment by austinksmith** [comment]
It appears you have not read any of the documentation, please visit https://www.hamsters.io/wiki/basics to understand how the library works. It doesn't appear that you are even telling the library to run a function in your usage of the library, what is your expected result?

**Comment by daoxian** [comment]
> It appears you have not read any of the documentation, please visit https://www.hamsters.io/wiki/basics to understand how the library works. It doesn't appear that you are even telling the library to run a function in your usage of the library, what is your expected result? The library was built and optimized around the v8 engine running in Chrome. Please take a look at the provided example demonstration https://www.hamsters.io/examples/collatz_conjecture

OMG, the docs are so complicated, and I need register an account first...  The codes should be self-explained, and I don't think I should pick some lib that spends lots of my time looking at the docs.  I'll choose some other simpler libs and bye...

**Comment by austinksmith** [comment]
The documentation should be very easy for you to follow, this library is quite complex and deals with a complex subject matter which is parallel processing. It requires you to read the documentation to understand how to make use of it, also the code has jsdoc standard comments explaining what each method does and the inputs it accepts. 

Regarding account creation, this is true because I have dealt with some malicious individuals stealing not only my code and claiming it was theirs but also making an exact copy of the website and naming it something else and then defaming the library and I was forced to hire a lawyer to defend the library and myself from these attacks and also received death threats from the same individuals.

It only takes a few seconds to create an account and you can view the documentation, perhaps you are new to software development. You will find that reading the documentation for almost any library is going to help you actual understand how it works and how to make the best use of it, you should have an easy understanding of this library within 5 minutes of reading the docs...
